config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  devise_for :users
  root to: "plans#index"
  resources :plans
  resources :messages, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :plans
  has_many :messages
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  with_options presence: true do
    validates :nickname
    validates :family_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/ }
    validates :family_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birth_day
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :password, :password_confirmation, :nickname, :family_name, :first_name,:family_name_kana, :first_name_kana, :birth_day ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.all.order('created_at DESC')
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path
    else
      @messages = messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def create
    @plan = Plan.create(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end

  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to plan_path(@plan)
    else
      render 'edit'
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    if current_user.id == @plan.user_id
      @plan.destroy
      redirect_to root_path
    else
      render :show
    end
  end
  private

  def plan_params
    params.require(:plan).permit(:site_name, :place, :period, :start_time, :number_of_people, :belongings, :phone_number, :car, :prefecture_id).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_bar">
        <div class="header_nav">
          <div class="menu_icon" id="lists">
            <%= image_tag "/assets/sozai_cman_jp_20210221152543.png", class: "menu_image" %>
            <ul class="navbar_lists  hidden" id="pull-down">
              <li class="navbar_list"><%= link_to "ホーム", root_path %> </li>
              <li class="navbar_list"><%= link_to "チャット", messages_path %></li>
              <% if user_signed_in? %>
                <li class="navbar_list"><%= link_to current_user.nickname, edit_user_registration_path(current_user), class: "user-nickname" %></li>
                <li class="navbar_list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li class="navbar_list"><%= link_to "ログイン", new_user_session_path %></li>
                <li class="navbar_list"><%= link_to "新規登録", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="heading">
        <h1 class="header_logo"><a href="/">ScheduleManagement</a></h1>
      </div>
    </header>

    <%= yield %>
    
    <footer>
      <p>
        Copyright ScheduleManagement 2021.
      </p>
    </footer>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="message-wrapper">
  <div class="chat-header">
    <div class="left-header-title">
      チャットルーム
    </div>

    <div class="right-header">
      <div class="header-button">
        <%= link_to "チャットを終了する", root_path %>
      </div>
    </div>
  </div>

  <div class="messages">
    <%= render partial: 'message', collection: @messages %>
  </div>

  <%= form_with model: @message, class: 'form', local: true do |f| %>
    <div class="form-input">
      <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
      <label class="form-image">
        <span class="image-file">画像</span>
        <%= f.file_field :image, class: 'hidden' %>
      </label>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>
</div>

app/views/plans/_main_plan.html.erb
<div class="btn-new-plans">
<%=link_to("/plans/new") do %>
  <button class="btn btn-new-plan" >予定を追加する</button>
<%end%>
</div>

<%= month_calendar events: @plans do |date, plans| %>
  <%= date.day %>

  <% plans.each do |plan| %>
    <div>
      <%= link_to plan.site_name, plan %>
    </div>
  <% end %>
<% end %>

app/views/plans/edit.html.erb
<div class="wrapper">
  <div class="schedule_change">

    <h1>予定変更</h1>

    <%= form_with(model: @plan, local: true) do |form| %>

      <div class="edit_plans">

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :現場名 %>
          </div>
            <%= form.text_field :site_name, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :場所 %>
          </div>
            <%= form.text_field :place, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :期間 %>
          </div>
            <%= form.text_field :period, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :着工日時 %>
          </div>
          <div class="new-text-fields">
            <%= form.datetime_select :start_time %>
          </div>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :人数 %>
          </div>
            <%= form.text_field :number_of_people, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :持ち物 %>
          </div>
            <%= form.text_field :belongings, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :連絡先電話番号 %>
          </div>
            <%= form.text_field :phone_number, class:'edit-text-field' %>
        </div>

        <div class="edit_plan">
          <div class="edit-label">
            <%= form.label :使用している車両 %>
          </div>
            <%= form.text_field :car, class:'edit-text-field' %>
        </div>

        <div class="edit_plan_submit">
          <div class="edit_submit">
            <%= form.submit %>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/plans/index.html.erb
<div class="wrapper">
  <%= month_calendar events: @plans do |date, plans| %>
    <%= date.day %>

    <% plans.each do |plan| %>
      <div>
        <%= link_to plan.site_name, plan %>
      </div>
    <% end %>
  <% end %>

  <div class="btn-new-plans">
    <%=link_to("/plans/new") do %>
      <button class="btn btn-new-plan" >予定を追加する</button>
    <%end%>
    <%= link_to(messages_path) do %>
      <button class="btn btn-index-message" >チャットする</button>
    <%end%>
  </div>
</div>

app/views/plans/new.html.erb
<div class="wrapper">
  <div class="schedule_addition">

    <h1>予定追加</h1>

    <%= form_with(model: @plan, local: true) do |form| %>

      <div class="new_plans">

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :現場名 %>
          </div>
            <%= form.text_field :site_name, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :場所 %>
          </div>
            <%= form.text_field :place, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :期間 %>
          </div>
            <%= form.text_field :period, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :着工日時 %>
          </div>
          <div class="new-text-fields">
            <%= form.datetime_select :start_time %>
          </div>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :人数 %>
          </div>
            <%= form.text_field :number_of_people, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :持ち物 %>
          </div>
            <%= form.text_field :belongings, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :連絡先電話番号 %>
          </div>
            <%= form.text_field :phone_number, class:'new-text-field' %>
        </div>

        <div class="new_plan">
          <div class="new-label">
            <%= form.label :使用している車両 %>
          </div>
            <%= form.text_field :car, class:'new-text-field' %>
        </div>

        <div class="new_plan_submit">
          <div class="new_submit">
            <%= form.submit %>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/plans/show.html.erb
<div class="wrapper">
  <div class="schedule_details">
    <h1>予定詳細</h1>

    <div class="show_plans">
      <div class="show_plan">
        <div class="show_plan_title">
          現場名
        </div>
        <div class="show_plan_name">
          <%= @plan.site_name %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          場所
        </div>
        <div class="show_plan_name">
          <%= @plan.place %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          期間
        </div>
        <div class="show_plan_name">
          <%= @plan.period %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          着工日時
        </div>
        <div class="show_plan_name">
          <%= @plan.start_time.strftime("%Y-%m-%d %H:%M") %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          人数
        </div>
        <div class="show_plan_name">
          <%= @plan.number_of_people %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          持ち物
        </div>
        <div class="show_plan_name">
          <%= @plan.belongings %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          連絡先電話番号
        </div>
        <div class="show_plan_name">
          <%= @plan.phone_number %>
        </div>
      </div>

      <div class="show_plan">
        <div class="show_plan_title">
          使用している車両
        </div>
        <div class="show_plan_name">
          <%= @plan.car %>
        </div>
      </div>
    </div>
    <div class="link_show_plans">
      <div>
      <%# justify-content: space-around;の調整の為です %>
      </div>
      <%if user_signed_in?%>
        <% if current_user.id == @plan.user_id %>
          <%= link_to(edit_plan_path) do %>
            <button class="btn btn-edit-plan" >内容を変更する</button>
          <%end%>
          |
          <%= link_to(plan_path(@plan.id), method: :delete) do %>
            <button class="btn btn-destroy-plan" >内容を削除する</button>
          <%end%>
        <%else%>
          <%= link_to(root_path) do %>
            <button class="btn btn-root-plan" >ホーム画面へ戻る</button>
          <%end%>
        <%end%>
      <%else%>
        <%= link_to(root_path) do %>
              <button class="btn btn-root-plan" >ホーム画面へ戻る</button>
        <%end%>
      <%end%>
      <div>
      <%# justify-content: space-around;の調整の為です %>
      </div>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<< Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next >>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>